Added Custom App Bar Component
zwalone/FUD pull request #1
Opened 2021-04-27 11:48 UTC by MKamil99

Implemented custom App Bar with a "Recipes" title and clickable SearchIcon, which is responsible for showing Search Bar. All of the colors are taken from the Figma project.

![image](https://user-images.githubusercontent.com/43967269/116236087-ea06a300-a75e-11eb-9b60-63c3bb586b88.png)
![image](https://user-images.githubusercontent.com/43967269/116236127-f7bc2880-a75e-11eb-85eb-554934ecbad4.png)

2021-04-27 12:31 UTC, Madoxen requested changes

2021-04-27 12:31 UTC, Madoxen commented on src/components/CustomAppBar.js
> +
Couple things to correct:
- Add callback when the user is submitting the search
- Make app bar header not selectable by user

2021-04-27 15:22 UTC, MKamil99 commented
New display:

![image](https://user-images.githubusercontent.com/43967269/116267735-f7cb2100-a77c-11eb-9029-0420c36c06ce.png)
![image](https://user-images.githubusercontent.com/43967269/116267781-01548900-a77d-11eb-96df-0c237fa894c5.png)
![image](https://user-images.githubusercontent.com/43967269/116267829-0a455a80-a77d-11eb-91b7-b962dc17e4f0.png)

2021-04-27 15:22 UTC, MellerB commented on src/components/CustomAppBar.js
> +import ArrowBackIcon from '@material-ui/icons/ArrowBack';
default importów unikamy jak ognia!!!

2021-04-27 15:23 UTC, MellerB commented on src/components/CustomAppBar.js
> +    const searchButtonEvent = () => props.search(searchBarInput.current.value);
nie ma potrzeby komentowania wszystkego jak szalony 
//a teraz zrobię zmienną toster
toster = zróbToster()

2021-04-27 15:31 UTC, MellerB commented on src/components/CustomAppBar.js
> +import ArrowBackIcon from '@material-ui/icons/ArrowBack';
import React, { useState } from 'react';
import { makeStyles } from '@material-ui/core/styles';
import {IconButton, AppBar, Toolbar, Typography, InputBase, IconButton} from '@material-ui/core'
import {SearchIcon, CloseIcon} from '@material-ui/icons'

2021-04-28 11:01 UTC, Madoxen approved these changes

2021-04-28 11:01 UTC, Madoxen commented
Fine by me :)

2021-04-28 11:01 UTC, merged